# Generated by Django 2.2 on 2020-01-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Staff')], max_length=50, verbose_name='Role'),
        ),
    ]
