# Generated by Django 2.2 on 2020-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_auto_20200113_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=50, verbose_name='Role'),
        ),
    ]
