# Generated by Django 2.2 on 2020-01-07 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('REQUEST', 'Request'), ('FAILURE', 'Failure')], default='REQUEST', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, default=False, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.Equipment')),
                ('status_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.Status')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
