# Generated by Django 2.2 on 2020-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(choices=[('REQUEST', 'Request'), ('FAILURE', 'Failure')], default='REQUEST', max_length=20)),
                ('start_date', models.DateField(blank=True, default=False, null=True)),
                ('start_time', models.TimeField(blank=True, default=False, null=True)),
                ('end_date', models.DateField(blank=True, default=False, null=True)),
                ('end_time', models.TimeField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
