# Generated by Django 2.2 on 2020-01-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_auto_20200129_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
