# Generated by Django 2.2 on 2020-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_status_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
