# Generated by Django 2.2 on 2020-02-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_auto_20200204_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
