# Generated by Django 2.2 on 2020-01-27 08:02

import Equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='no',
            field=models.IntegerField(default=Equipment.models.Equipment.ids, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
