# Generated by Django 2.2 on 2020-01-27 09:10

import Equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_auto_20200127_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='locate',
            name='no',
            field=models.IntegerField(default=Equipment.models.Locate.ids, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='locate',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
