# Generated by Django 2.2 on 2020-02-18 03:45

import Equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0004_locate_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesifikasi',
            fields=[
                ('no', models.IntegerField(default=Equipment.models.Spesifikasi.ids, editable=False, unique=True, verbose_name='Code')),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
