# Generated by Django 2.2 on 2020-02-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0005_spesifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lebar',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='merek',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='panjang',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tinggi',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
