# Generated by Django 2.2 on 2020-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0007_auto_20200219_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesifikasi',
            name='s10',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 10'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s2',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 2'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s3',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 3'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s4',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 4'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s5',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 5'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s6',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 6'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s7',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 7'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s8',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 8'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s9',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 9'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs10',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 10'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs2',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 2'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs3',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 3'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs4',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 4'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs5',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 5'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs6',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 6'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs7',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 7'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs8',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 8'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs9',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 9'),
        ),
    ]
