# Generated by Django 2.2 on 2020-02-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0008_auto_20200219_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesifikasi',
            name='s11',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 11'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='s12',
            field=models.CharField(max_length=100, null=True, verbose_name='Spesifikasi 12'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs11',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 11'),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='vs12',
            field=models.CharField(max_length=100, null=True, verbose_name='Value 12'),
        ),
    ]
