# Generated by Django 2.2 on 2020-02-19 03:45

import Equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0009_auto_20200219_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eqp_img_pic',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=Equipment.models.img_url, verbose_name='Equipment Picture'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supliyer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
