# Generated by Django 2.2 on 2020-02-19 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0010_auto_20200219_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesifikasi',
            name='eqp_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipment.Equipment'),
        ),
    ]
